apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: product-service
        version: {{ .Values.productservice.deployment.tag }}
    spec:
      containers:
        - name: product-service
          image: {{ .Values.productservice.deployment.image }}:{{ .Values.productservice.deployment.tag }}
          imagePullPolicy: Always
          resources:
            limits:
              memory: 128M
              cpu: .1
          env:
            - name: MONGO_HOST
              value: "mongo-mongodb"
          ports:
            - containerPort: 3000
