apiVersion: v1
kind: Service
metadata:
  name: product-service
  annotations:
spec:
  type: LoadBalancer
  selector:
    app: product-service
  ports:
    - name: product-service-port
      protocol: TCP
      port: 3000
      targetPort: 3000
